image: node:16.11.1

variables:
  NODE_ENV: "gitlab"

before_script:
  - npm install -g pnpm@7.18.0
  - pnpm config set store-dir .pnpm-store

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store/
    - node_modules/
    - .next/cache/

pages:
  script:
    - pnpm install && pnpm build && pnpm run export
    - rm -rf public && mkdir public
    - cp -r out/* public/.
  artifacts:
    paths:
      - public
  only:
    - main
